version: '3'
services:
  workspace:
    image: ghcr.io/andyli/debian_packaging_devcontainer:master
    init: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ./.devscripts:/home/vscode/.devscripts
      - ./.sbuildrc:/home/vscode/.sbuildrc
      - ./.quiltrc:/home/vscode/.quiltrc
      - ./dput.cf:/home/vscode/.config/dput/dput.cf
      - ./timezone:/etc/timezone
      - ..:/workspace:cached
      - ../../debian:/workspace/projects:cached
      - schroot-session:/var/lib/schroot/session
      - schroot-union-overlay:/var/lib/schroot/union/overlay
      - sbuild-build:/var/lib/sbuild/build
    environment:
      - EARTHLY_USE_INLINE_CACHE=true
      - EARTHLY_SAVE_INLINE_CACHE=true
      - GIT_EDITOR=code --wait
    user: vscode
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

volumes:
  schroot-session:
    driver_opts:
      type: tmpfs
      device: tmpfs
  schroot-union-overlay:
    driver_opts:
      type: tmpfs
      device: tmpfs
  sbuild-build:
    driver_opts:
      type: tmpfs
      device: tmpfs
